# config.toml
[connection]
account = "SYSJHTT-SU12818" # e.g., abcd12345.ap-south-1 (check your Snowflake URL)
user = "RUFFI"
password = "snow!RUFFI22!!"
role = "SYSADMIN" # e.g., SYSADMIN, ANALYST_ROLE
warehouse = "ML_TRAINING_WH" # e.g., COMPUTE_WH
database = "M5_FORECASTING" # e.g., M5_FORECASTING_DB
schema = "DBT_DEV" # e.g., RAW_DATA or ANALYTICS
# Optional:
# client_session_keep_alive = true


